# Functions in pandas

Let's import a dataset using pandas function.
The function read_csv reads the dataset from a csv file. There are also other functions for different file like read_excel.

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('Water_pond_tanks_2021.csv',encoding='cp1252')

# data = pd.to_csv("")

Pandas registers the data read from a dataset as a dataframe by default

In [ ]:
data

,STN\nCode,Name of Monitoring Location,Type Water Body,State Name,Temperature\n?C (Min),Temperature\n?C (Max),Dissolved Oxygen (mg/L) (Min),Dissolved Oxygen (mg/L) (Max),pH (Min),pH (Max),Conductivity (?mhos/cm) (Min),Conductivity (?mhos/cm) (Max),BOD (mg/L) (Min),BOD (mg/L) (Max),Nitrate N + Nitrite N(mg/L) (Min),Nitrate N + Nitrite N(mg/L) (Max),Fecal Coliform (MPN/100ml) (Min),Fecal Coliform (MPN/100ml) (Max),Total Coliform (MPN/100ml) (Min),Total Coliform (MPN/100ml) (Max)
0,4368.0,"KOLLERU LAKE KOKKIRAYALANKA (V), KAILALUR (M)",LAKE,ANDHRA PRADESH,24.0,27.0,3.2,6.5,7.0,8.0,245,5160,1.6,3.2,1.02,3.60,9,21,120,210
1,2353.0,"KONDAKARLA-AAVA LAKE, PARAWADA PHARMA CITY, VI...",LAKE,ANDHRA PRADESH,26.0,29.0,3.0,6.8,6.9,7.8,599,1179,1.9,4.6,0.77,3.56,15,23,150,240
2,1790.0,"PULICATE LAKE , NELLORE DIST",LAKE,ANDHRA PRADESH,18.0,24.0,4.2,6.0,7.2,8.2,28000,56900,2.4,2.8,1.20,1.64,3,3,47,150
3,4391.0,"CHENGAMBAKAM TANK IN SRI CITY SEZ,\nTIRUPATHI",TANK,ANDHRA PRADESH,22.0,29.0,5.4,6.2,6.3,7.9,180,476,1.0,2.5,0.34,2.30,24,365,170,549
4,4921.0,ANNAMAYYA PROJECT ON CHEYYERU\nRESERVOIR,Wetland,ANDHRA PRADESH,21.0,30.0,5.4,6.5,7.3,8.0,496,734,1.0,2.3,0.35,1.00,43,289,240,727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,1765.0,"RABINDRASAROVAR NATIONAL LAKE,\nCALCUTTA, WEST...",LAKE,WEST BENGAL,22.0,31.0,5.2,9.7,7.2,8.5,252,826,1.8,4.1,0.30,1.90,330,790,1100,1700
616,2544.0,SAHEBBANDH AT PURULIA,LAKE,WEST BENGAL,22.0,32.0,8.8,9.8,7.0,7.6,311,422,2.7,7.3,0.30,0.80,3100,9400,4300,12000
617,2522.0,SINCHAL LAKE FOR DARJEELING,LAKE,WEST BENGAL,7.0,16.0,7.1,8.1,6.9,7.6,13,29,1.0,1.1,0.30,0.30,70,110,110,210
618,2521.0,"WATER RESERVIOR AT DELO LAKE,\nDARJELLING",LAKE,WEST BENGAL,9.0,24.0,7.2,8.2,6.9,7.6,20,36,1.0,1.8,0.30,0.30,60,130,110,330
619,4725.0,WATER RESERVIOR ST. HELENS SCHOOL,LAKE,WEST BENGAL,8.0,18.0,7.1,8.5,6.9,7.9,16,73,1.0,1.6,0.30,0.30,70,110,110,330

The rows in the above dataframe are called samples(if it is a subset of a large dataset) or dataset instances(if you consider the whole population).

**In machine learning terminology, the columns are called features of the dataset.**

In [ ]:
#To get the features, i.e. columns in the dataset
data.columns

Index(['STN\nCode', 'Name of Monitoring Location', 'Type Water Body',
       'State Name', 'Temperature\n?C (Min)', 'Temperature\n?C (Max)',
       'Dissolved Oxygen (mg/L) (Min)', 'Dissolved Oxygen (mg/L) (Max)',
       'pH (Min)', 'pH (Max)', 'Conductivity (?mhos/cm) (Min)',
       'Conductivity (?mhos/cm) (Max)', 'BOD (mg/L) (Min)', 'BOD (mg/L) (Max)',
       'Nitrate N + Nitrite N(mg/L) (Min)',
       'Nitrate N + Nitrite N(mg/L) (Max)', 'Fecal Coliform (MPN/100ml) (Min)',
       'Fecal Coliform (MPN/100ml) (Max)', 'Total Coliform (MPN/100ml) (Min)',
       'Total Coliform (MPN/100ml) (Max)'],
      dtype='object')

To rename the columns we can use rename function

In [ ]:
data.rename(columns = {"Name of Monitoring Location": "Monitoring Location"},inplace=True)
data

,STN\nCode,Monitoring Location,Type Water Body,State Name,Temperature\n?C (Min),Temperature\n?C (Max),Dissolved Oxygen (mg/L) (Min),Dissolved Oxygen (mg/L) (Max),pH (Min),pH (Max),Conductivity (?mhos/cm) (Min),Conductivity (?mhos/cm) (Max),BOD (mg/L) (Min),BOD (mg/L) (Max),Nitrate N + Nitrite N(mg/L) (Min),Nitrate N + Nitrite N(mg/L) (Max),Fecal Coliform (MPN/100ml) (Min),Fecal Coliform (MPN/100ml) (Max),Total Coliform (MPN/100ml) (Min),Total Coliform (MPN/100ml) (Max)
0,4368.0,"KOLLERU LAKE KOKKIRAYALANKA (V), KAILALUR (M)",LAKE,ANDHRA PRADESH,24.0,27.0,3.2,6.5,7.0,8.0,245,5160,1.6,3.2,1.02,3.60,9,21,120,210
1,2353.0,"KONDAKARLA-AAVA LAKE, PARAWADA PHARMA CITY, VI...",LAKE,ANDHRA PRADESH,26.0,29.0,3.0,6.8,6.9,7.8,599,1179,1.9,4.6,0.77,3.56,15,23,150,240
2,1790.0,"PULICATE LAKE , NELLORE DIST",LAKE,ANDHRA PRADESH,18.0,24.0,4.2,6.0,7.2,8.2,28000,56900,2.4,2.8,1.20,1.64,3,3,47,150
3,4391.0,"CHENGAMBAKAM TANK IN SRI CITY SEZ,\nTIRUPATHI",TANK,ANDHRA PRADESH,22.0,29.0,5.4,6.2,6.3,7.9,180,476,1.0,2.5,0.34,2.30,24,365,170,549
4,4921.0,ANNAMAYYA PROJECT ON CHEYYERU\nRESERVOIR,Wetland,ANDHRA PRADESH,21.0,30.0,5.4,6.5,7.3,8.0,496,734,1.0,2.3,0.35,1.00,43,289,240,727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,1765.0,"RABINDRASAROVAR NATIONAL LAKE,\nCALCUTTA, WEST...",LAKE,WEST BENGAL,22.0,31.0,5.2,9.7,7.2,8.5,252,826,1.8,4.1,0.30,1.90,330,790,1100,1700
616,2544.0,SAHEBBANDH AT PURULIA,LAKE,WEST BENGAL,22.0,32.0,8.8,9.8,7.0,7.6,311,422,2.7,7.3,0.30,0.80,3100,9400,4300,12000
617,2522.0,SINCHAL LAKE FOR DARJEELING,LAKE,WEST BENGAL,7.0,16.0,7.1,8.1,6.9,7.6,13,29,1.0,1.1,0.30,0.30,70,110,110,210
618,2521.0,"WATER RESERVIOR AT DELO LAKE,\nDARJELLING",LAKE,WEST BENGAL,9.0,24.0,7.2,8.2,6.9,7.6,20,36,1.0,1.8,0.30,0.30,60,130,110,330
619,4725.0,WATER RESERVIOR ST. HELENS SCHOOL,LAKE,WEST BENGAL,8.0,18.0,7.1,8.5,6.9,7.9,16,73,1.0,1.6,0.30,0.30,70,110,110,330

The functions head and tail give a peek of the dataset

In [ ]:
data.head(10)

,STN\nCode,Monitoring Location,Type Water Body,State Name,Temperature\n?C (Min),Temperature\n?C (Max),Dissolved Oxygen (mg/L) (Min),Dissolved Oxygen (mg/L) (Max),pH (Min),pH (Max),Conductivity (?mhos/cm) (Min),Conductivity (?mhos/cm) (Max),BOD (mg/L) (Min),BOD (mg/L) (Max),Nitrate N + Nitrite N(mg/L) (Min),Nitrate N + Nitrite N(mg/L) (Max),Fecal Coliform (MPN/100ml) (Min),Fecal Coliform (MPN/100ml) (Max),Total Coliform (MPN/100ml) (Min),Total Coliform (MPN/100ml) (Max)
0,4368.0,"KOLLERU LAKE KOKKIRAYALANKA (V), KAILALUR (M)",LAKE,ANDHRA PRADESH,24.0,27.0,3.2,6.5,7.0,8.0,245,5160,1.6,3.2,1.02,3.60,9,21,120,210
1,2353.0,"KONDAKARLA-AAVA LAKE, PARAWADA PHARMA CITY, VI...",LAKE,ANDHRA PRADESH,26.0,29.0,3.0,6.8,6.9,7.8,599,1179,1.9,4.6,0.77,3.56,15,23,150,240
2,1790.0,"PULICATE LAKE , NELLORE DIST",LAKE,ANDHRA PRADESH,18.0,24.0,4.2,6.0,7.2,8.2,28000,56900,2.4,2.8,1.20,1.64,3,3,47,150
3,4391.0,"CHENGAMBAKAM TANK IN SRI CITY SEZ,\nTIRUPATHI",TANK,ANDHRA PRADESH,22.0,29.0,5.4,6.2,6.3,7.9,180,476,1.0,2.5,0.34,2.30,24,365,170,549
4,4921.0,ANNAMAYYA PROJECT ON CHEYYERU\nRESERVOIR,Wetland,ANDHRA PRADESH,21.0,30.0,5.4,6.5,7.3,8.0,496,734,1.0,2.3,0.35,1.00,43,289,240,727
5,4936.0,ANUMANAPALLE CHERUVU,Wetland,ANDHRA PRADESH,22.0,23.0,6.8,7.5,7.1,9.0,158,320,1.2,2.2,0.42,1.79,3,4,63,150
6,4919.0,BRAMHASAGAR,Wetland,ANDHRA PRADESH,20.0,29.0,5.1,6.4,7.1,7.9,381,608,1.0,2.2,0.32,0.67,45,322,210,602
7,4926.0,DALI TANK,Wetland,ANDHRA PRADESH,22.0,31.0,4.2,7.3,7.1,8.5,274,18950,1.5,2.5,0.38,2.82,4,15,2,150
8,4931.0,GACCHAKAYALA PORA (LAGOON),Wetland,ANDHRA PRADESH,27.0,31.0,4.5,7.2,7.1,8.6,12230,56900,1.4,3.6,0.63,2.86,4,15,64,120
9,4917.0,GANGINENI CHERUVU,Wetland,ANDHRA PRADESH,21.0,30.0,3.8,5.8,6.6,8.1,802,1326,2.2,3.5,1.08,4.51,191,659,540,1120

In [ ]:
data.tail(7)

,STN\nCode,Monitoring Location,Type Water Body,State Name,Temperature\n?C (Min),Temperature\n?C (Max),Dissolved Oxygen (mg/L) (Min),Dissolved Oxygen (mg/L) (Max),pH (Min),pH (Max),Conductivity (?mhos/cm) (Min),Conductivity (?mhos/cm) (Max),BOD (mg/L) (Min),BOD (mg/L) (Max),Nitrate N + Nitrite N(mg/L) (Min),Nitrate N + Nitrite N(mg/L) (Max),Fecal Coliform (MPN/100ml) (Min),Fecal Coliform (MPN/100ml) (Max),Total Coliform (MPN/100ml) (Min),Total Coliform (MPN/100ml) (Max)
613,2504.0,"MAINH GHAT ON DUDHPUKUR AT TARAKESHWAR, HOOGHLY",LAKE,WEST BENGAL,22.5,34.0,3.8,12.0,7.6,8.7,569,775,3.6,7.2,0.30,0.90,13000,240000,23000,540000
614,2520.0,"MIRIKH LAKE, DARJEELING",LAKE,WEST BENGAL,4.0,24.0,5.8,6.9,6.5,8.0,67,196,1.8,2.8,0.30,0.32,2100,5000,5000,14000
615,1765.0,"RABINDRASAROVAR NATIONAL LAKE,\nCALCUTTA, WEST...",LAKE,WEST BENGAL,22.0,31.0,5.2,9.7,7.2,8.5,252,826,1.8,4.1,0.30,1.90,330,790,1100,1700
616,2544.0,SAHEBBANDH AT PURULIA,LAKE,WEST BENGAL,22.0,32.0,8.8,9.8,7.0,7.6,311,422,2.7,7.3,0.30,0.80,3100,9400,4300,12000
617,2522.0,SINCHAL LAKE FOR DARJEELING,LAKE,WEST BENGAL,7.0,16.0,7.1,8.1,6.9,7.6,13,29,1.0,1.1,0.30,0.30,70,110,110,210
618,2521.0,"WATER RESERVIOR AT DELO LAKE,\nDARJELLING",LAKE,WEST BENGAL,9.0,24.0,7.2,8.2,6.9,7.6,20,36,1.0,1.8,0.30,0.30,60,130,110,330
619,4725.0,WATER RESERVIOR ST. HELENS SCHOOL,LAKE,WEST BENGAL,8.0,18.0,7.1,8.5,6.9,7.9,16,73,1.0,1.6,0.30,0.30,70,110,110,330

The shape function provides information about the dimensions of the dataset

In [ ]:
data.shape

(620, 20)

The info function provides you with the general structure of the dataset

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 620 entries, 0 to 619
Data columns (total 20 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   STN
Code                           619 non-null    float64
 1   Monitoring Location                620 non-null    object
 2   Type Water Body                    620 non-null    object
 3   State Name                         620 non-null    object
 4   Temperature
?C (Min)               617 non-null    float64
 5   Temperature
?C (Max)               617 non-null    float64
 6   Dissolved Oxygen (mg/L) (Min)      620 non-null    object
 7   Dissolved Oxygen (mg/L) (Max)      620 non-null    object
 8   pH (Min)                           620 non-null    object
 9   pH (Max)                           620 non-null    float64
 10  Conductivity (?mhos/cm) (Min)      618 non-null    object
 11  Conductivity (?mhos/cm) (Max)      618 non-null    object
 12  BOD (mg/L) (Min)                   620 non-null    object
 13  BOD (mg/L) (Max)                   620 non-null    object
 14  Nitrate N + Nitrite N(mg/L) (Min)  620 non-null    object
 15  Nitrate N + Nitrite N(mg/L) (Max)  620 non-null    object
 16  Fecal Coliform (MPN/100ml) (Min)   619 non-null    object
 17  Fecal Coliform (MPN/100ml) (Max)   619 non-null    object
 18  Total Coliform (MPN/100ml) (Min)   619 non-null    object
 19  Total Coliform (MPN/100ml) (Max)   619 non-null    object
dtypes: float64(4), object(16)
memory usage: 97.0+ KB

The function isna returns boolean value for each datapoint in the dataset i.e. either true or false by checking whether a number is NaN or not

NaN , standing for not a number, is a numeric data type used to represent any value that is undefined or unpresentable. For example, 0/0 is undefined as a real number and is, therefore, represented by NaN.

In [ ]:
data.isna()

,STN\nCode,Monitoring Location,Type Water Body,State Name,Temperature\n?C (Min),Temperature\n?C (Max),Dissolved Oxygen (mg/L) (Min),Dissolved Oxygen (mg/L) (Max),pH (Min),pH (Max),Conductivity (?mhos/cm) (Min),Conductivity (?mhos/cm) (Max),BOD (mg/L) (Min),BOD (mg/L) (Max),Nitrate N + Nitrite N(mg/L) (Min),Nitrate N + Nitrite N(mg/L) (Max),Fecal Coliform (MPN/100ml) (Min),Fecal Coliform (MPN/100ml) (Max),Total Coliform (MPN/100ml) (Min),Total Coliform (MPN/100ml) (Max)
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
616,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
617,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
618,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
619,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

The describe function provides you with the information about the statistics of variables like count, mean, standard deviation, etc

The 25%, 50%, 75% values are called quartiles of a dataset. Quartiles are the set of values which has three points dividing the data set into four identical parts.

In [ ]:
data.describe()

         STN\nCode  Temperature\n?C (Min)  Temperature\n?C (Max)    pH (Max)
count   619.000000             617.000000             617.000000  620.000000
mean   3442.067851              21.805186              28.374716    8.029194
std    1065.368325               4.657455               3.647189    0.492039
min    1263.000000               4.000000              16.000000    6.700000
25%    2530.500000              20.000000              25.000000    7.600000
50%    3619.000000              22.000000              28.000000    8.000000
75%    4352.500000              25.000000              30.300000    8.400000
max    5063.000000              34.000000              42.000000   10.300000

The function nunique provides total number of unique values in each column of the dataframe

In [ ]:
data.nunique()
#Eg State name tells us there are 32 unique values of states i.e., we have 32 states under consideration

STN\nCode                            619
Monitoring Location                  615
Type Water Body                        4
State Name                            32
Temperature\n?C (Min)                 59
Temperature\n?C (Max)                 53
Dissolved Oxygen (mg/L) (Min)         79
Dissolved Oxygen (mg/L) (Max)        107
pH (Min)                              31
pH (Max)                              30
Conductivity (?mhos/cm) (Min)        443
Conductivity (?mhos/cm) (Max)        509
BOD (mg/L) (Min)                      63
BOD (mg/L) (Max)                     135
Nitrate N + Nitrite N(mg/L) (Min)    147
Nitrate N + Nitrite N(mg/L) (Max)    287
Fecal Coliform (MPN/100ml) (Min)     115
Fecal Coliform (MPN/100ml) (Max)     186
Total Coliform (MPN/100ml) (Min)     137
Total Coliform (MPN/100ml) (Max)     149
dtype: int64

The function unique provides with all the unique values for a particular column in the dataframe

In [ ]:
data['Type Water Body'].unique()

array(['LAKE', 'TANK', 'Wetland', 'POND'], dtype=object)

The value_counts functions will return the count for each unique value present in the dataset

In [ ]:
data['Monitoring Location'].value_counts()

GOTTIGERE LAKE                       2
PEDDA CHERUVU                        2
MANCHANABALE DAM                     2
HEBBAL LAKE                          2
RAMAMMANA KERE                       2
                                    ..
PARAPPANA AGRAHARA LAKE              1
PATTANDUR AGARAHARA                  1
PUTTENAHALLI LAKE                    1
PUTTENAHALLI LAKE (S)                1
WATER RESERVIOR ST. HELENS SCHOOL    1
Name: Monitoring Location, Length: 615, dtype: int64

The drop function can be used to drop the column.

In [ ]:
data = data.drop(['Monitoring Location'], axis=1)
data.head()

,STN\nCode,Type Water Body,State Name,Temperature\n?C (Min),Temperature\n?C (Max),Dissolved Oxygen (mg/L) (Min),Dissolved Oxygen (mg/L) (Max),pH (Min),pH (Max),Conductivity (?mhos/cm) (Min),Conductivity (?mhos/cm) (Max),BOD (mg/L) (Min),BOD (mg/L) (Max),Nitrate N + Nitrite N(mg/L) (Min),Nitrate N + Nitrite N(mg/L) (Max),Fecal Coliform (MPN/100ml) (Min),Fecal Coliform (MPN/100ml) (Max),Total Coliform (MPN/100ml) (Min),Total Coliform (MPN/100ml) (Max)
0,4368.0,LAKE,ANDHRA PRADESH,24.0,27.0,3.2,6.5,7.0,8.0,245,5160,1.6,3.2,1.02,3.60,9,21,120,210
1,2353.0,LAKE,ANDHRA PRADESH,26.0,29.0,3.0,6.8,6.9,7.8,599,1179,1.9,4.6,0.77,3.56,15,23,150,240
2,1790.0,LAKE,ANDHRA PRADESH,18.0,24.0,4.2,6.0,7.2,8.2,28000,56900,2.4,2.8,1.20,1.64,3,3,47,150
3,4391.0,TANK,ANDHRA PRADESH,22.0,29.0,5.4,6.2,6.3,7.9,180,476,1.0,2.5,0.34,2.30,24,365,170,549
4,4921.0,Wetland,ANDHRA PRADESH,21.0,30.0,5.4,6.5,7.3,8.0,496,734,1.0,2.3,0.35,1.00,43,289,240,727

The function iloc takes as a parameter the rows and column indices and gives you the subset of the DataFrame accordingly

In [ ]:
data.iloc[:10,1:4]

  Type Water Body      State Name  Temperature\n?C (Min)
0            LAKE  ANDHRA PRADESH                   24.0
1            LAKE  ANDHRA PRADESH                   26.0
2            LAKE  ANDHRA PRADESH                   18.0
3            TANK  ANDHRA PRADESH                   22.0
4         Wetland  ANDHRA PRADESH                   21.0
5         Wetland  ANDHRA PRADESH                   22.0
6         Wetland  ANDHRA PRADESH                   20.0
7         Wetland  ANDHRA PRADESH                   22.0
8         Wetland  ANDHRA PRADESH                   27.0
9         Wetland  ANDHRA PRADESH                   21.0

The function loc() does almost the similar operation as iloc() function, but here we can specify exactly which row index we want and also the name of the columns we want in our subset

In [ ]:
data.loc[[200],['Type Water Body','State Name']]

    Type Water Body State Name
200            LAKE  KARNATAKA

The dtypes tells us about the datatype that each column has

In [ ]:
data.dtypes

STN\nCode                            float64
Type Water Body                       object
State Name                            object
Temperature\n?C (Min)                float64
Temperature\n?C (Max)                float64
Dissolved Oxygen (mg/L) (Min)         object
Dissolved Oxygen (mg/L) (Max)         object
pH (Min)                              object
pH (Max)                             float64
Conductivity (?mhos/cm) (Min)         object
Conductivity (?mhos/cm) (Max)         object
BOD (mg/L) (Min)                      object
BOD (mg/L) (Max)                      object
Nitrate N + Nitrite N(mg/L) (Min)     object
Nitrate N + Nitrite N(mg/L) (Max)     object
Fecal Coliform (MPN/100ml) (Min)      object
Fecal Coliform (MPN/100ml) (Max)      object
Total Coliform (MPN/100ml) (Min)      object
Total Coliform (MPN/100ml) (Max)      object
dtype: object

The insert function to insert a random column

In [ ]:
import numpy as np
random_col = np.random.randint(100, size=len(data))

data.insert(2, 'random_col', random_col)
data

,STN\nCode,Type Water Body,random_col,State Name,Temperature\n?C (Min),Temperature\n?C (Max),Dissolved Oxygen (mg/L) (Min),Dissolved Oxygen (mg/L) (Max),pH (Min),pH (Max),Conductivity (?mhos/cm) (Min),Conductivity (?mhos/cm) (Max),BOD (mg/L) (Min),BOD (mg/L) (Max),Nitrate N + Nitrite N(mg/L) (Min),Nitrate N + Nitrite N(mg/L) (Max),Fecal Coliform (MPN/100ml) (Min),Fecal Coliform (MPN/100ml) (Max),Total Coliform (MPN/100ml) (Min),Total Coliform (MPN/100ml) (Max)
0,4368.0,LAKE,55,ANDHRA PRADESH,24.0,27.0,3.2,6.5,7.0,8.0,245,5160,1.6,3.2,1.02,3.60,9,21,120,210
1,2353.0,LAKE,49,ANDHRA PRADESH,26.0,29.0,3.0,6.8,6.9,7.8,599,1179,1.9,4.6,0.77,3.56,15,23,150,240
2,1790.0,LAKE,85,ANDHRA PRADESH,18.0,24.0,4.2,6.0,7.2,8.2,28000,56900,2.4,2.8,1.20,1.64,3,3,47,150
3,4391.0,TANK,55,ANDHRA PRADESH,22.0,29.0,5.4,6.2,6.3,7.9,180,476,1.0,2.5,0.34,2.30,24,365,170,549
4,4921.0,Wetland,27,ANDHRA PRADESH,21.0,30.0,5.4,6.5,7.3,8.0,496,734,1.0,2.3,0.35,1.00,43,289,240,727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,1765.0,LAKE,63,WEST BENGAL,22.0,31.0,5.2,9.7,7.2,8.5,252,826,1.8,4.1,0.30,1.90,330,790,1100,1700
616,2544.0,LAKE,63,WEST BENGAL,22.0,32.0,8.8,9.8,7.0,7.6,311,422,2.7,7.3,0.30,0.80,3100,9400,4300,12000
617,2522.0,LAKE,88,WEST BENGAL,7.0,16.0,7.1,8.1,6.9,7.6,13,29,1.0,1.1,0.30,0.30,70,110,110,210
618,2521.0,LAKE,62,WEST BENGAL,9.0,24.0,7.2,8.2,6.9,7.6,20,36,1.0,1.8,0.30,0.30,60,130,110,330
619,4725.0,LAKE,42,WEST BENGAL,8.0,18.0,7.1,8.5,6.9,7.9,16,73,1.0,1.6,0.30,0.30,70,110,110,330

In [ ]:
data.head()

,STN\nCode,Type Water Body,random_col,State Name,Temperature\n?C (Min),Temperature\n?C (Max),Dissolved Oxygen (mg/L) (Min),Dissolved Oxygen (mg/L) (Max),pH (Min),pH (Max),Conductivity (?mhos/cm) (Min),Conductivity (?mhos/cm) (Max),BOD (mg/L) (Min),BOD (mg/L) (Max),Nitrate N + Nitrite N(mg/L) (Min),Nitrate N + Nitrite N(mg/L) (Max),Fecal Coliform (MPN/100ml) (Min),Fecal Coliform (MPN/100ml) (Max),Total Coliform (MPN/100ml) (Min),Total Coliform (MPN/100ml) (Max)
0,4368.0,LAKE,55,ANDHRA PRADESH,24.0,27.0,3.2,6.5,7.0,8.0,245,5160,1.6,3.2,1.02,3.60,9,21,120,210
1,2353.0,LAKE,49,ANDHRA PRADESH,26.0,29.0,3.0,6.8,6.9,7.8,599,1179,1.9,4.6,0.77,3.56,15,23,150,240
2,1790.0,LAKE,85,ANDHRA PRADESH,18.0,24.0,4.2,6.0,7.2,8.2,28000,56900,2.4,2.8,1.20,1.64,3,3,47,150
3,4391.0,TANK,55,ANDHRA PRADESH,22.0,29.0,5.4,6.2,6.3,7.9,180,476,1.0,2.5,0.34,2.30,24,365,170,549
4,4921.0,Wetland,27,ANDHRA PRADESH,21.0,30.0,5.4,6.5,7.3,8.0,496,734,1.0,2.3,0.35,1.00,43,289,240,727

The sample function will randomly sample 100 datapoints from the dataset

In [ ]:
data.sample(100)

,STN\nCode,Type Water Body,random_col,State Name,Temperature\n?C (Min),Temperature\n?C (Max),Dissolved Oxygen (mg/L) (Min),Dissolved Oxygen (mg/L) (Max),pH (Min),pH (Max),Conductivity (?mhos/cm) (Min),Conductivity (?mhos/cm) (Max),BOD (mg/L) (Min),BOD (mg/L) (Max),Nitrate N + Nitrite N(mg/L) (Min),Nitrate N + Nitrite N(mg/L) (Max),Fecal Coliform (MPN/100ml) (Min),Fecal Coliform (MPN/100ml) (Max),Total Coliform (MPN/100ml) (Min),Total Coliform (MPN/100ml) (Max)
50,1263.0,POND,45,ASSAM,19.0,29.0,4.0,6.8,7.0,7.6,206,882,2.2,2.8,0.80,1.30,300,910,730,2100
281,3599.0,TANK,31,KARNATAKA,25.0,25.0,3.4,6.6,6.2,7.6,213,1240,2.0,13.0,0.56,3.80,2300,460000,24000,3500000
189,3611.0,LAKE,59,KARNATAKA,25.0,25.0,0.3,7.2,6.6,7.7,629,1449,3.0,27.0,0.93,6.00,2200,1700000,24000,16000000
30,1529.0,LAKE,33,ASSAM,20.0,31.0,4.2,10.8,7.2,7.8,150,291,2.2,5.2,0.80,1.80,300,730,910,1600
271,3588.0,TANK,77,KARNATAKA,19.0,26.0,6.0,7.4,7.4,8.6,496,764,2.5,6.0,1.50,3.20,700,1100,4300,5800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561,2348.0,TANK,92,TELANGANA,20.0,25.0,4.0,5.6,7.0,7.3,1428,3964,5.0,10.0,12.20,21.15,2,8,39,63
177,3654.0,LAKE,29,KARNATAKA,25.0,26.0,2.1,6.8,6.1,7.1,240,2720,3.0,34.0,0.30,8.80,4000,120000,24000,920000
605,3437.0,LAKE,79,UTTARAKHAND,11.0,23.0,7.4,9.0,7.2,8.0,160,210,1.0,1.6,0.32,0.37,70,170,210,540
59,4006.0,POND,42,ASSAM,18.0,35.0,5.0,7.6,6.0,7.9,64,88,1.8,2.6,0.70,1.10,300,360,360,910
298,3565.0,TANK,45,KARNATAKA,28.0,30.0,4.9,7.9,6.5,7.2,128,224,2.0,3.0,2.10,7.00,23,1600,23,1600

The replace function is used to replace all occurences of the given value with the new value.

In [ ]:
data.replace({21.0 : 20.0})
data.head()
#data.replace({1.260 : 1.120, 5.555 : 0.435, 1.724 : 2.675})

,STN\nCode,Type Water Body,random_col,State Name,Temperature\n?C (Min),Temperature\n?C (Max),Dissolved Oxygen (mg/L) (Min),Dissolved Oxygen (mg/L) (Max),pH (Min),pH (Max),Conductivity (?mhos/cm) (Min),Conductivity (?mhos/cm) (Max),BOD (mg/L) (Min),BOD (mg/L) (Max),Nitrate N + Nitrite N(mg/L) (Min),Nitrate N + Nitrite N(mg/L) (Max),Fecal Coliform (MPN/100ml) (Min),Fecal Coliform (MPN/100ml) (Max),Total Coliform (MPN/100ml) (Min),Total Coliform (MPN/100ml) (Max)
0,4368.0,LAKE,55,ANDHRA PRADESH,24.0,27.0,3.2,6.5,7.0,8.0,245,5160,1.6,3.2,1.02,3.60,9,21,120,210
1,2353.0,LAKE,49,ANDHRA PRADESH,26.0,29.0,3.0,6.8,6.9,7.8,599,1179,1.9,4.6,0.77,3.56,15,23,150,240
2,1790.0,LAKE,85,ANDHRA PRADESH,18.0,24.0,4.2,6.0,7.2,8.2,28000,56900,2.4,2.8,1.20,1.64,3,3,47,150
3,4391.0,TANK,55,ANDHRA PRADESH,22.0,29.0,5.4,6.2,6.3,7.9,180,476,1.0,2.5,0.34,2.30,24,365,170,549
4,4921.0,Wetland,27,ANDHRA PRADESH,21.0,30.0,5.4,6.5,7.3,8.0,496,734,1.0,2.3,0.35,1.00,43,289,240,727

Changing Datatype of a column

In [ ]:
data['random_col'] = data['random_col'].astype(float)
print(data.dtypes)

STN\nCode                            float64
Type Water Body                       object
random_col                           float64
State Name                            object
Temperature\n?C (Min)                float64
Temperature\n?C (Max)                float64
Dissolved Oxygen (mg/L) (Min)         object
Dissolved Oxygen (mg/L) (Max)         object
pH (Min)                              object
pH (Max)                             float64
Conductivity (?mhos/cm) (Min)         object
Conductivity (?mhos/cm) (Max)         object
BOD (mg/L) (Min)                      object
BOD (mg/L) (Max)                      object
Nitrate N + Nitrite N(mg/L) (Min)     object
Nitrate N + Nitrite N(mg/L) (Max)     object
Fecal Coliform (MPN/100ml) (Min)      object
Fecal Coliform (MPN/100ml) (Max)      object
Total Coliform (MPN/100ml) (Min)      object
Total Coliform (MPN/100ml) (Max)      object
dtype: object